# Auto-generated built-in question pool for SharedMoments Daily Questions.
# 365 curated German prompts: one full year without requiring AI.

CATEGORY_LABELS = {'alltag': 'Alltag',
 'locker_lustig': 'Locker & lustig',
 'erinnerungen': 'Erinnerungen',
 'zukunft': 'Zukunft & Träume',
 'liebe_naehe': 'Liebe & Nähe',
 'dankbarkeit': 'Dankbarkeit',
 'beziehung_wir': 'Unser Wir',
 'reisen_erlebnisse': 'Reisen & Erlebnisse',
 'zuhause_rituale': 'Zuhause & Rituale',
 'persoenlichkeit': 'Über dich'}

BUILTIN_QUESTIONS = [('alltag', 'Was war heute bisher dein schönster kleiner Moment?'),
 ('alltag', 'Was würde deinen heutigen Tag sofort ein bisschen besser machen?'),
 ('alltag', 'Welche Kleinigkeit können wir diese Woche gemeinsam erledigen, damit sie sich leichter anfühlt?'),
 ('alltag', 'Worauf freust du dich gerade am meisten?'),
 ('alltag', 'Was hat dich heute zum Lächeln gebracht?'),
 ('alltag', 'Was war heute anstrengender, als es von außen aussah?'),
 ('alltag', 'Welche Sache möchtest du heute Abend auf keinen Fall mehr erledigen müssen?'),
 ('alltag', 'Was wäre heute die perfekte Art, den Tag gemeinsam ausklingen zu lassen?'),
 ('alltag', 'Welche kleine Aufmerksamkeit würde dir diese Woche guttun?'),
 ('alltag', 'Was beschäftigt dich gerade mehr, als du eigentlich möchtest?'),
 ('alltag', 'Was ist momentan dein liebster Teil unseres Alltags?'),
 ('alltag', 'Welche Aufgabe würdest du heute am liebsten an mich abgeben?'),
 ('alltag', 'Wofür hattest du diese Woche bisher zu wenig Zeit?'),
 ('alltag', 'Was möchtest du am kommenden Wochenende unbedingt machen – auch wenn es nur etwas Kleines ist?'),
 ('alltag', 'Was war heute überraschend angenehm?'),
 ('alltag', 'Welche Gewohnheit macht deinen Alltag gerade besser?'),
 ('alltag', 'Was sollten wir im Alltag öfter spontan machen?'),
 ('alltag', 'Was möchtest du diese Woche bewusst langsamer angehen?'),
 ('alltag', 'Was gibt dir nach einem langen Tag am schnellsten neue Energie?'),
 ('alltag', 'Welche gemeinsame Mahlzeit könnten wir bald mal wieder machen?'),
 ('alltag', 'Welcher Moment am Tag fühlt sich für dich am meisten nach Zuhause an?'),
 ('alltag', 'Was würdest du gern öfter zusammen machen, ohne dass wir es groß planen müssen?'),
 ('alltag', 'Was fehlt dir diese Woche noch, damit sie sich rund anfühlt?'),
 ('alltag', 'Welche Sache schiebst du gerade vor dir her?'),
 ('alltag', 'Was war heute dein unnötigster Stressmoment?'),
 ('alltag', 'Was möchtest du morgen auf jeden Fall anders machen als heute?'),
 ('alltag', 'Welche kleine Routine von uns magst du besonders?'),
 ('alltag', 'Was hilft dir am besten, wenn dein Kopf voll ist?'),
 ('alltag', 'Welche Sache sollten wir diesen Monat endlich abhaken?'),
 ('alltag', 'Was wäre heute ein perfekter Snack für uns beide?'),
 ('alltag', 'Welche alltägliche Sache macht zu zweit deutlich mehr Spaß?'),
 ('alltag', 'Was würdest du heute gern hören: Rat, Ablenkung oder einfach Zustimmung?'),
 ('alltag', 'Welche Nachricht von mir freut dich im Alltag immer?'),
 ('alltag', 'Was könnten wir an einem ganz normalen Dienstag tun, damit er besonders wird?'),
 ('alltag', 'Was ist gerade dein liebstes kleines Luxusgefühl im Alltag?'),
 ('alltag', 'Welche Ecke unseres Alltags könnten wir ein bisschen einfacher organisieren?'),
 ('alltag', 'Was möchtest du diese Woche unbedingt noch genießen?'),
 ('alltag', 'Welche Sache hast du heute gut gemacht, auf die du ein bisschen stolz sein kannst?'),
 ('alltag', 'Was ist gerade das Erste, woran du denkst, wenn du Feierabend hörst?'),
 ('alltag', 'Welche gemeinsame Routine sollten wir unbedingt behalten?'),
 ('alltag', 'Was wäre für dich ein perfekter fauler Abend?'),
 ('alltag', 'Was möchtest du gerade lieber: rausgehen oder zuhause bleiben – und warum?'),
 ('alltag', 'Welche Kleinigkeit darf diese Woche ruhig liegen bleiben?'),
 ('alltag', 'Was würde uns im Alltag gerade zehn Prozent mehr Leichtigkeit bringen?'),
 ('alltag', 'Welches gemeinsame Essen geht für dich eigentlich immer?'),
 ('alltag', 'Was ist momentan deine liebste Tageszeit?'),
 ('alltag', 'Welche kleine Sache von mir erleichtert dir manchmal den Alltag?'),
 ('alltag', 'Was sollten wir öfter einfach machen, statt lange darüber zu reden?'),
 ('alltag', 'Was wäre heute eine gute Mini-Auszeit für uns?'),
 ('alltag', 'Welche Sache möchtest du diese Woche nur für dich tun?'),
 ('locker_lustig', 'Wenn wir heute spontan irgendwo essen müssten: Döner, Pizza, Sushi oder etwas ganz anderes?'),
 ('locker_lustig', 'Welche meiner Angewohnheiten wäre in einer Sitcom ein Running Gag?'),
 ('locker_lustig', 'Wenn wir für einen Tag die Rollen tauschen würden: Was wäre für dich am lustigsten?'),
 ('locker_lustig', 'Welches völlig unnötige Ding würdest du sofort kaufen, wenn Geld egal wäre?'),
 ('locker_lustig', 'Wenn unser Alltag eine Serie wäre: Wie würde die heutige Folge heißen?'),
 ('locker_lustig', 'Welches Tier beschreibt uns als Paar überraschend gut?'),
 ('locker_lustig', 'Wenn wir morgen 10.000 Euro an einem einzigen Tag ausgeben müssten: Wofür?'),
 ('locker_lustig', 'Welche drei Dinge müssten in unserem gemeinsamen Snack-Notfallkoffer sein?'),
 ('locker_lustig', 'Was wäre unser schlechtester gemeinsamer Beruf?'),
 ('locker_lustig', 'Wenn wir zusammen in einer Gameshow antreten würden: In welcher hätten wir die besten Chancen?'),
 ('locker_lustig', 'Welche berühmte Film- oder Serienwohnung würdest du sofort mit mir beziehen?'),
 ('locker_lustig', 'Wenn du mir heute einen völlig übertriebenen Spitznamen geben müsstest: welchen?'),
 ('locker_lustig', 'Welche absurde Regel würdest du für einen Tag bei uns zuhause einführen?'),
 ('locker_lustig', 'Wenn wir einen Foodtruck hätten: Was würden wir verkaufen?'),
 ('locker_lustig', 'Welche Sache würden wir bei einer Zombie-Apokalypse wahrscheinlich als Erstes falsch machen?'),
 ('locker_lustig', 'Wenn wir ein gemeinsames Maskottchen hätten: Was wäre es?'),
 ('locker_lustig', 'Welche drei Songs dürften auf einer peinlich guten Autofahrt-Playlist nicht fehlen?'),
 ('locker_lustig', 'Wenn wir spontan bei einem Pubquiz landen: Für welche Kategorie wärst du zuständig?'),
 ('locker_lustig', 'Welcher kleine Luxus ist deiner Meinung nach komplett überbewertet?'),
 ('locker_lustig', 'Welche völlig harmlose Sache nervt dich irrational stark?'),
 ('locker_lustig', 'Wenn unser Kühlschrank sprechen könnte: Was würde er über uns erzählen?'),
 ('locker_lustig', 'Welche Superkraft wäre im gemeinsamen Alltag am praktischsten?'),
 ('locker_lustig', 'Wenn wir einen Tag lang nur Essen aus einer Farbe essen dürften: Welche Farbe würdest du wählen?'),
 ('locker_lustig', 'Was wäre ein lustiger Name für unser gemeinsames Café?'),
 ('locker_lustig', 'Welche Modephase von dir würdest du am liebsten aus allen Fotos löschen?'),
 ('locker_lustig', 'Wenn wir in einer Realityshow wären: Wie würde sie heißen?'),
 ('locker_lustig', 'Welche Sache kannst du erstaunlich gut, obwohl sie komplett nutzlos ist?'),
 ('locker_lustig', 'Wenn du morgen mit einem neuen Hobby aufwachen würdest: Welches wäre lustig?'),
 ('locker_lustig', 'Welche fünf Euro wären heute maximal sinnvoll verschwendet?'),
 ('locker_lustig', 'Wenn wir nur noch ein Brett- oder Kartenspiel besitzen dürften: welches?'),
 ('locker_lustig', 'Welche fiktive Figur wäre ein schrecklicher Mitbewohner für uns?'),
 ('locker_lustig', 'Was wäre unser Signature-Drink – mit oder ohne Alkohol?'),
 ('locker_lustig', 'Wenn wir eine gemeinsame Band gründen müssten: Wie würde sie heißen?'),
 ('locker_lustig', 'Welche App würdest du sofort erfinden, wenn du könntest?'),
 ('locker_lustig', 'Wenn wir einen gemeinsamen YouTube-Kanal hätten: Worum würde es gehen?'),
 ('locker_lustig', 'Welche berühmte Person würdest du gern einmal mit uns zum Abendessen einladen?'),
 ('locker_lustig', 'Was war dein lustigster Fehlkauf?'),
 ('locker_lustig', 'Wenn wir heute Abend Karaoke machen müssten: Welchen Song würdest du wählen?'),
 ('locker_lustig', 'Welche Kleinigkeit kann dich zuverlässig zum Lachen bringen?'),
 ('locker_lustig', 'Wenn wir ein eigenes Feiertagsritual erfinden würden: Wie sähe es aus?'),
 ('locker_lustig', 'Welche Sache würdest du gern einmal ausprobieren, obwohl du ziemlich sicher schlecht darin wärst?'),
 ('locker_lustig', 'Wenn wir zusammen ein Restaurant eröffnen: Was steht garantiert nicht auf der Karte?'),
 ('locker_lustig',
  'Welche drei Dinge würdest du auf eine einsame Insel mitnehmen, wenn praktische Antworten verboten wären?'),
 ('locker_lustig', 'Wenn wir nur noch eine Streamingserie gemeinsam schauen dürften: welche?'),
 ('locker_lustig', 'Welche erfundene Auszeichnung hättest du dieses Jahr verdient?'),
 ('locker_lustig', 'Wenn unser Paar eine Wetterlage wäre: welche?'),
 ('locker_lustig', 'Welche Sache wirkt bei anderen völlig normal, aber bei uns würde sie garantiert chaotisch enden?'),
 ('locker_lustig',
  'Wenn wir eine Zeitmaschine nur für einen albernen Zweck benutzen dürften: wohin würden wir reisen?'),
 ('locker_lustig', 'Welche Essenskombination verteidigst du, obwohl andere sie komisch finden?'),
 ('locker_lustig', 'Wenn wir heute eine spontane Challenge machen müssten: Welche würdest du gewinnen?'),
 ('locker_lustig', 'Welche Sache würdest du gern einmal zusammen bauen, obwohl wir vermutlich fluchen würden?'),
 ('locker_lustig', 'Wenn du mir ein Meme beschreiben müsstest, das gerade zu uns passt: wie sähe es aus?'),
 ('locker_lustig', 'Welche Regel aus deiner Kindheit würdest du heute sofort abschaffen?'),
 ('locker_lustig', 'Wenn wir uns als Duo verkleiden müssten: als was?'),
 ('locker_lustig', 'Was wäre eine komplett unnötige, aber großartige Anschaffung für uns beide?'),
 ('erinnerungen', 'An welchen gemeinsamen Tag denkst du besonders gern zurück?'),
 ('erinnerungen', 'Welcher unserer ersten gemeinsamen Momente ist dir noch besonders klar im Kopf?'),
 ('erinnerungen', 'Was war bisher unser schönster spontaner Ausflug?'),
 ('erinnerungen', 'Welcher gemeinsame Urlaubsmoment bringt dich sofort zum Lächeln?'),
 ('erinnerungen', 'Welche Erinnerung an uns überrascht dich, weil sie sich so deutlich eingeprägt hat?'),
 ('erinnerungen', 'Was war unser bisher lustigster gemeinsamer Abend?'),
 ('erinnerungen', 'Welches gemeinsame Essen verbindest du sofort mit einer schönen Erinnerung?'),
 ('erinnerungen', 'Welche kleine Situation von früher bedeutet dir heute mehr als damals?'),
 ('erinnerungen', 'Was war das erste Detail an mir, das dir wirklich aufgefallen ist?'),
 ('erinnerungen', 'Welche gemeinsame Panne ist im Nachhinein eine gute Geschichte geworden?'),
 ('erinnerungen', 'An welchen gemeinsamen Sonntag erinnerst du dich besonders gern?'),
 ('erinnerungen', 'Welcher Song bringt dich sofort zu einem bestimmten Moment mit mir zurück?'),
 ('erinnerungen', 'Was war bisher unser gemütlichster gemeinsamer Tag?'),
 ('erinnerungen', 'Welche Reise oder welcher Ausflug hat uns deiner Meinung nach besonders gutgetan?'),
 ('erinnerungen', 'Was war eine Situation, in der wir zusammen überraschend gut funktioniert haben?'),
 ('erinnerungen', 'Welche Erinnerung würdest du gern noch einmal exakt so erleben?'),
 ('erinnerungen', 'Welches gemeinsame Foto magst du besonders – und warum?'),
 ('erinnerungen', 'Was war unser schönster ungeplanter Moment?'),
 ('erinnerungen', 'Welche Erinnerung an unsere Anfangszeit macht dich heute noch glücklich?'),
 ('erinnerungen', 'Was war ein Moment, in dem du dachtest: Das passt gerade einfach?'),
 ('erinnerungen', 'Welche gemeinsame Tradition ist eher zufällig entstanden?'),
 ('erinnerungen', 'An welches Gespräch mit mir erinnerst du dich noch besonders gut?'),
 ('erinnerungen', 'Welche kleine Geste von mir ist dir bis heute im Gedächtnis geblieben?'),
 ('erinnerungen', 'Was war bisher unser bester gemeinsamer Geburtstag oder Feiertag?'),
 ('erinnerungen', 'Welche Erinnerung wäre ein perfektes Kapitel in einem Buch über uns?'),
 ('erinnerungen', 'Was war ein Moment, in dem wir beide komplett die Zeit vergessen haben?'),
 ('erinnerungen', 'Welcher gemeinsame Ort ist für dich besonders stark mit einer Erinnerung verbunden?'),
 ('erinnerungen', 'Welche unserer gemeinsamen Entscheidungen war rückblickend besonders gut?'),
 ('erinnerungen', 'Was war unser bisher entspanntester Urlaubstag?'),
 ('erinnerungen', 'Welche Erinnerung zeigt für dich am besten, wie wir als Team sind?'),
 ('erinnerungen', 'Was war das erste gemeinsame Ritual, das sich wirklich nach uns angefühlt hat?'),
 ('erinnerungen', 'An welchen Regentag mit mir erinnerst du dich?'),
 ('erinnerungen', 'Welche Erinnerung von uns würdest du gern aus meiner Perspektive sehen?'),
 ('erinnerungen', 'Was war ein Moment, in dem wir über etwas völlig Unwichtiges sehr lachen mussten?'),
 ('erinnerungen', 'Welche gemeinsame Erinnerung erzählt du anderen besonders gern?'),
 ('erinnerungen', 'Was war ein Tag, der unscheinbar angefangen hat und dann richtig schön wurde?'),
 ('erinnerungen', 'Welche Erinnerung mit Familie oder Freunden verbindest du besonders mit uns als Paar?'),
 ('erinnerungen', 'Was war bisher unser schönstes gemeinsames Geschenk – unabhängig vom Preis?'),
 ('erinnerungen', 'Welche Erinnerung würde sich perfekt als kleines Video zusammenschneiden lassen?'),
 ('erinnerungen',
  'Welchen gemeinsamen Moment sollten wir unbedingt noch besser dokumentieren, solange wir uns erinnern?'),
 ('erinnerungen', 'Was war ein Moment, in dem du dich mit mir besonders sicher gefühlt hast?'),
 ('erinnerungen', 'Welche alte Nachricht von mir würdest du gern noch einmal lesen?'),
 ('erinnerungen', 'Was war die erste gemeinsame Sache, auf die wir uns richtig gefreut haben?'),
 ('erinnerungen', 'Welche Erinnerung zeigt am besten unseren Humor?'),
 ('erinnerungen', 'Welchen gemeinsamen Moment würdest du gern unserem zukünftigen Ich zeigen?'),
 ('zukunft', 'Was möchtest du in den nächsten zwölf Monaten unbedingt mit mir erleben?'),
 ('zukunft', 'Welcher Ort steht ganz oben auf deiner Wunschliste für uns?'),
 ('zukunft', 'Wie sieht für dich ein richtig gutes gemeinsames Wochenende in einem Jahr aus?'),
 ('zukunft', 'Was sollten wir irgendwann unbedingt gemeinsam lernen?'),
 ('zukunft', 'Welche Reise würdest du planen, wenn Zeit und Geld keine Rolle spielen?'),
 ('zukunft', 'Welche kleine Veränderung würde unser gemeinsames Leben in Zukunft schöner machen?'),
 ('zukunft', 'Was möchtest du, dass wir in fünf Jahren noch genauso machen wie heute?'),
 ('zukunft', 'Welche gemeinsame Anschaffung würde dir wirklich Freude machen?'),
 ('zukunft', 'Was wäre ein Projekt, das wir irgendwann zusammen starten könnten?'),
 ('zukunft', 'Welches Erlebnis möchtest du mindestens einmal im Leben mit mir teilen?'),
 ('zukunft', 'Wo würdest du gern einmal einen ganzen Monat mit mir verbringen?'),
 ('zukunft', 'Was möchtest du in unserer nächsten gemeinsamen Reise anders machen als bisher?'),
 ('zukunft', 'Welche Tradition könnten wir dieses Jahr neu anfangen?'),
 ('zukunft', 'Was wäre ein schönes Ziel für uns bis zum Jahresende?'),
 ('zukunft', 'Welche Sache sollten wir uns für später auf keinen Fall immer nur aufheben?'),
 ('zukunft', 'Wie stellst du dir einen perfekten gemeinsamen freien Tag in fünf Jahren vor?'),
 ('zukunft', 'Was würdest du gern einmal mit mir feiern, das kein klassischer Feiertag ist?'),
 ('zukunft', 'Welche Stadt möchtest du mit mir unbedingt zu Fuß entdecken?'),
 ('zukunft', 'Welche gemeinsame Fähigkeit wäre praktisch, wenn wir sie beide könnten?'),
 ('zukunft', 'Was wäre ein Traum, der klein genug ist, dass wir ihn dieses Jahr wirklich umsetzen können?'),
 ('zukunft', 'Welche Art von Zuhause würde sich für dich langfristig gut anfühlen?'),
 ('zukunft', 'Was möchtest du in Zukunft öfter mit mir besprechen, bevor der Alltag dazwischenkommt?'),
 ('zukunft', 'Welches gemeinsame Abenteuer klingt heute noch ein bisschen verrückt, aber reizvoll?'),
 ('zukunft', 'Was sollten wir in zehn Jahren über unsere heutige Zeit sagen können?'),
 ('zukunft', 'Welche Sache möchtest du irgendwann einmal für uns selbst machen statt kaufen?'),
 ('zukunft', 'Was wäre ein schöner gemeinsamer Jahresvorsatz ohne Leistungsdruck?'),
 ('zukunft', 'Welche Erfahrung möchtest du mit mir machen, bevor wir deutlich älter sind?'),
 ('zukunft', 'Wo würdest du gern einmal mit mir den Sonnenaufgang sehen?'),
 ('zukunft', 'Was könnte ein zukünftiges Ritual für einen besonderen Jahrestag sein?'),
 ('zukunft', 'Welche gemeinsame Erinnerung fehlt uns deiner Meinung nach noch?'),
 ('zukunft', 'Was würdest du gern einmal mit mir besuchen: Konzert, Festival, Theater, Sport oder etwas anderes?'),
 ('zukunft', 'Welche Art von Reise sollten wir mindestens einmal ausprobieren?'),
 ('zukunft', 'Was möchtest du, dass unser Zuhause in Zukunft mehr ausstrahlt?'),
 ('zukunft', 'Welche gemeinsame Gewohnheit könnten wir in den nächsten Monaten aufbauen?'),
 ('zukunft', 'Was würdest du gern einmal mit mir kochen, obwohl es ziemlich aufwendig ist?'),
 ('zukunft', 'Welche Sache wollen wir irgendwann erzählen können: Das haben wir wirklich zusammen gemacht?'),
 ('zukunft', 'Was wäre ein guter nächster Schritt für einen gemeinsamen Wunsch, den wir schon länger haben?'),
 ('zukunft', 'Welche Jahreszeit würdest du gern einmal komplett an einem anderen Ort erleben?'),
 ('zukunft', 'Welche gemeinsame Herausforderung würdest du dir mit mir zutrauen?'),
 ('zukunft', 'Was wäre ein schönes Geschenk an unser zukünftiges Ich?'),
 ('zukunft', 'Welche Sache möchtest du in den kommenden Jahren unbedingt bewahren?'),
 ('zukunft', 'Wo sollten wir irgendwann ein gemeinsames Foto machen, das heute noch fehlt?'),
 ('zukunft', 'Welche Idee für uns verdient es, endlich vom Vielleicht zum Plan zu werden?'),
 ('zukunft', 'Was wäre ein perfekter Anlass für einen spontanen Kurztrip?'),
 ('zukunft', 'Wenn wir nächstes Jahr nur ein großes gemeinsames Erlebnis planen: Welches sollte es sein?'),
 ('liebe_naehe', 'Wann hast du dich zuletzt besonders von mir gesehen gefühlt?'),
 ('liebe_naehe', 'Welche Art von Nähe tut dir am meisten gut, wenn du einen schwierigen Tag hattest?'),
 ('liebe_naehe', 'Welche Kleinigkeit an mir magst du besonders?'),
 ('liebe_naehe', 'Was lässt dich bei uns am schnellsten zur Ruhe kommen?'),
 ('liebe_naehe', 'Woran merkst du im Alltag, dass ich dich liebe?'),
 ('liebe_naehe', 'Welche Form von Zuneigung bedeutet dir besonders viel?'),
 ('liebe_naehe', 'Was kann ich tun, damit du dich nach einem stressigen Tag schneller willkommen fühlst?'),
 ('liebe_naehe', 'Welcher Moment zwischen uns fühlt sich für dich besonders vertraut an?'),
 ('liebe_naehe', 'Was bedeutet Geborgenheit in unserer Beziehung für dich?'),
 ('liebe_naehe', 'Welche Berührung von mir magst du im Alltag besonders?'),
 ('liebe_naehe', 'Was würdest du gern öfter von mir hören?'),
 ('liebe_naehe', 'Welche Sache zwischen uns fühlt sich angenehm selbstverständlich an?'),
 ('liebe_naehe', 'Was macht unsere Nähe für dich anders als zu Beginn unserer Beziehung?'),
 ('liebe_naehe', 'Wann fühlst du dich mir besonders verbunden?'),
 ('liebe_naehe', 'Welche kleine Geste sagt für dich mehr als ein großes Geschenk?'),
 ('liebe_naehe', 'Was hilft dir, wenn du dich zurückziehen möchtest, ohne dass wir uns voneinander entfernen?'),
 ('liebe_naehe', 'Welche Seite von mir kennst du vermutlich besser als fast alle anderen?'),
 ('liebe_naehe', 'Was ist etwas, das du an unserem Umgang miteinander sehr schätzt?'),
 ('liebe_naehe', 'Welche Art von gemeinsamem Abend fühlt sich für dich besonders nah an?'),
 ('liebe_naehe', 'Was kann ich tun, wenn du Trost brauchst, aber keine Lösung?'),
 ('liebe_naehe', 'Welche Eigenschaft von mir gibt dir Sicherheit?'),
 ('liebe_naehe', "Was bedeutet für dich ein gutes 'Wir-Gefühl'?"),
 ('liebe_naehe', 'Welche kleine Liebeserklärung passt besser zu uns als große Worte?'),
 ('liebe_naehe', 'Was ist ein Moment, in dem du dich von mir besonders unterstützt gefühlt hast?'),
 ('liebe_naehe', 'Welche Sache möchtest du, dass ich über deine Art, Liebe zu zeigen, immer im Kopf behalte?'),
 ('liebe_naehe',
  'Was empfindest du als unsere stärkste Form von Nähe: reden, lachen, berühren, zusammen etwas tun oder etwas '
  'anderes?'),
 ('liebe_naehe', 'Welche Komplimente von mir bleiben bei dir hängen?'),
 ('liebe_naehe', 'Was bedeutet Vertrauen in unserem Alltag ganz konkret für dich?'),
 ('liebe_naehe', 'Wann ist Schweigen zwischen uns angenehm?'),
 ('liebe_naehe', 'Was würdest du gern öfter gemeinsam tun, nur weil es sich gut anfühlt?'),
 ('liebe_naehe', 'Welche Seite unserer Beziehung möchtest du besonders schützen?'),
 ('liebe_naehe', 'Was kann ich tun, damit du dich in hektischen Zeiten trotzdem mit mir verbunden fühlst?'),
 ('liebe_naehe', 'Welche meiner kleinen Gesten bemerkst du, auch wenn du nicht immer etwas dazu sagst?'),
 ('liebe_naehe', 'Was ist für dich romantischer als klassische Romantik?'),
 ('liebe_naehe', 'Welche Situation lässt dich denken: Genau dafür liebe ich unser Wir?'),
 ('liebe_naehe', 'Was sollten wir uns gegenseitig öfter erlauben?'),
 ('liebe_naehe', 'Welche Art von Aufmerksamkeit fühlt sich für dich besonders ehrlich an?'),
 ('liebe_naehe', 'Was ist etwas, das zwischen uns mit der Zeit schöner geworden ist?'),
 ('liebe_naehe', 'Wann hast du das Gefühl, dass wir uns ohne viele Worte verstehen?'),
 ('liebe_naehe', 'Welche Form von Unterstützung wünschst du dir von mir, wenn du unsicher bist?'),
 ('liebe_naehe', 'Was bedeutet Loyalität in unserer Beziehung für dich?'),
 ('liebe_naehe', 'Welche gemeinsame Nähe möchtest du auch im stressigsten Alltag nicht verlieren?'),
 ('liebe_naehe', 'Was ist eine Sache, bei der du dich auf mich verlassen kannst?'),
 ('liebe_naehe', 'Welche liebevolle Gewohnheit sollten wir nie aus Bequemlichkeit verlieren?'),
 ('liebe_naehe', 'Was möchtest du, dass ich heute über deine Gefühle weiß?'),
 ('dankbarkeit', 'Wofür bist du mir gerade besonders dankbar?'),
 ('dankbarkeit', 'Welche kleine Sache, die ich oft mache, schätzt du mehr, als ich vielleicht merke?'),
 ('dankbarkeit', 'Was hat uns in letzter Zeit gutgetan?'),
 ('dankbarkeit', 'Welche Eigenschaft von mir erleichtert dir unser gemeinsames Leben?'),
 ('dankbarkeit', 'Wofür bist du unserem Alltag gerade dankbar?'),
 ('dankbarkeit', 'Welche gemeinsame Erfahrung möchtest du nicht missen?'),
 ('dankbarkeit', 'Was habe ich in letzter Zeit gemacht, das dir positiv aufgefallen ist?'),
 ('dankbarkeit', 'Welche Stärke von uns als Paar schätzt du besonders?'),
 ('dankbarkeit', 'Was ist etwas an unserem Zuhause, für das du dankbar bist?'),
 ('dankbarkeit', 'Welche kleine Unterstützung von mir bedeutet dir viel?'),
 ('dankbarkeit', 'Was ist eine Sache, die wir zusammen inzwischen richtig gut können?'),
 ('dankbarkeit', 'Welche gemeinsame Entscheidung macht dich heute noch froh?'),
 ('dankbarkeit', 'Wofür bist du dir selbst in unserer Beziehung dankbar?'),
 ('dankbarkeit',
  'Welche Sache an mir nimmst du vielleicht manchmal als selbstverständlich, obwohl sie dir wichtig ist?'),
 ('dankbarkeit', 'Was ist ein Privileg unseres gemeinsamen Lebens, das wir öfter wahrnehmen könnten?'),
 ('dankbarkeit', 'Welche schwierige Phase hat uns rückblickend etwas Wertvolles gezeigt?'),
 ('dankbarkeit', 'Was hast du durch unsere Beziehung über dich selbst gelernt?'),
 ('dankbarkeit', 'Welche Erinnerung macht dich besonders dankbar dafür, dass wir sie teilen?'),
 ('dankbarkeit', 'Was schätzt du an der Art, wie wir miteinander lachen?'),
 ('dankbarkeit', 'Welche Alltagsaufgabe von mir entlastet dich mehr, als ich vermutlich denke?'),
 ('dankbarkeit', 'Was ist etwas, das wir füreinander tun, ohne groß darüber zu sprechen?'),
 ('dankbarkeit', 'Welche Seite von mir möchtest du heute ausdrücklich wertschätzen?'),
 ('dankbarkeit', 'Was findest du schön daran, wie wir Unterschiede miteinander aushalten?'),
 ('dankbarkeit', 'Wofür möchtest du unserem vergangenen Ich einmal Danke sagen?'),
 ('dankbarkeit', 'Welche gemeinsame Gewohnheit tut unserer Beziehung gut?'),
 ('dankbarkeit', 'Was ist etwas, das du an unserer Kommunikation schätzt?'),
 ('dankbarkeit', 'Welche Veränderung in unserer Beziehung empfindest du als positiv?'),
 ('dankbarkeit', 'Was ist ein Moment aus letzter Zeit, für den du dankbar bist?'),
 ('dankbarkeit', 'Welche meiner Entscheidungen hat dir einmal besonders geholfen?'),
 ('dankbarkeit', 'Was ist etwas, das du an unserem gemeinsamen Humor liebst?'),
 ('dankbarkeit', 'Wofür bist du dankbar, das man nicht kaufen kann?'),
 ('dankbarkeit', 'Welche Sache an unserem Leben würdest du niemals gegen etwas Größeres oder Teureres eintauschen?'),
 ('dankbarkeit', 'Was ist eine kleine Selbstverständlichkeit zwischen uns, die eigentlich ziemlich besonders ist?'),
 ('dankbarkeit', 'Wofür würdest du uns heute ein kleines Dankeschön aussprechen?'),
 ('dankbarkeit', 'Welche gemeinsame Sache macht dein Leben konkret schöner?'),
 ('beziehung_wir', 'Was funktioniert bei uns als Team besonders gut?'),
 ('beziehung_wir', 'Wo ergänzen wir uns deiner Meinung nach am besten?'),
 ('beziehung_wir', 'Welche gemeinsame Entscheidung treffen wir meistens gut?'),
 ('beziehung_wir', 'Was unterscheidet unser Wir positiv von anderen Beziehungen, die du kennst?'),
 ('beziehung_wir', 'Welche Sache könnten wir als Team noch besser machen?'),
 ('beziehung_wir', 'Wie merken wir beide am schnellsten, dass der andere gerade Unterstützung braucht?'),
 ('beziehung_wir', 'Was ist eine Stärke unserer Beziehung, die wir uns hart erarbeitet haben?'),
 ('beziehung_wir', 'Welche Unterschiede zwischen uns tun unserer Beziehung gut?'),
 ('beziehung_wir', 'Was sollten wir bei Meinungsverschiedenheiten öfter beachten?'),
 ('beziehung_wir', 'Welche gemeinsame Regel haben wir, obwohl wir sie nie offiziell ausgesprochen haben?'),
 ('beziehung_wir', 'Was bedeutet Fairness in unserer Beziehung für dich?'),
 ('beziehung_wir', 'Welche Sache sollten wir häufiger gemeinsam entscheiden statt nebenbei?'),
 ('beziehung_wir', 'Wo geben wir uns gegenseitig besonders viel Freiheit?'),
 ('beziehung_wir', 'Welche Art von Konflikt lösen wir heute besser als früher?'),
 ('beziehung_wir', 'Was sollte in unserem gemeinsamen Alltag immer Priorität behalten?'),
 ('beziehung_wir', 'Welche Sache über uns verstehen Außenstehende vielleicht nicht sofort?'),
 ('beziehung_wir', 'Was hilft uns, nach Stress wieder zueinanderzufinden?'),
 ('beziehung_wir', 'Welche gemeinsame Grenze ist dir wichtig?'),
 ('beziehung_wir', 'Was könnten wir tun, damit schwierige Themen leichter anzusprechen sind?'),
 ('beziehung_wir', 'Welche Seite unserer Beziehung ist stärker geworden?'),
 ('beziehung_wir', 'Wo sollten wir uns gegenseitig weniger Druck machen?'),
 ('beziehung_wir', 'Was ist für dich ein Zeichen dafür, dass wir ein gutes Team sind?'),
 ('beziehung_wir', 'Welche Aufgabe teilen wir deiner Meinung nach besonders fair?'),
 ('beziehung_wir', 'Was möchtest du, dass wir uns auch in zehn Jahren noch ehrlich sagen können?'),
 ('beziehung_wir', 'Welche Art von Entscheidung sollten wir nie treffen, wenn einer von uns müde oder gestresst ist?'),
 ('beziehung_wir', 'Was hilft dir, dich bei uns ernst genommen zu fühlen?'),
 ('beziehung_wir', 'Welche Sache sollten wir uns öfter gegenseitig zutrauen?'),
 ('beziehung_wir', 'Was bedeutet Verlässlichkeit zwischen uns für dich?'),
 ('beziehung_wir', 'Welche Situation zeigt, dass wir unterschiedlich sein dürfen und trotzdem gut zusammenpassen?'),
 ('beziehung_wir', 'Wo könnten wir uns im Alltag bewusster gegenseitig Raum geben?'),
 ('beziehung_wir', 'Was ist etwas, das wir als Paar nicht perfekt machen müssen?'),
 ('beziehung_wir', 'Welche Sache möchtest du, dass wir bei Veränderungen immer miteinander abstimmen?'),
 ('beziehung_wir', 'Was hilft uns, nicht nur zu funktionieren, sondern uns auch als Paar zu erleben?'),
 ('beziehung_wir', 'Welche gemeinsame Entscheidung würdest du jederzeit wieder treffen?'),
 ('beziehung_wir', 'Was möchtest du, dass unser zukünftiges Ich über unsere Beziehung heute sagen kann?'),
 ('reisen_erlebnisse', 'Welchen Ort würdest du morgen spontan mit mir besuchen, wenn wir frei hätten?'),
 ('reisen_erlebnisse', 'Was war bisher dein liebster gemeinsamer Reisetag?'),
 ('reisen_erlebnisse', 'Welche Art von Urlaub passt deiner Meinung nach am besten zu uns?'),
 ('reisen_erlebnisse', 'Meer, Berge, Stadt oder Land – was würdest du gerade wählen?'),
 ('reisen_erlebnisse', 'Welches Land möchtest du mit mir unbedingt einmal bereisen?'),
 ('reisen_erlebnisse', 'Welche Stadt hat dich positiv überrascht und wäre einen gemeinsamen Besuch wert?'),
 ('reisen_erlebnisse', 'Was darf auf einem gemeinsamen Roadtrip auf keinen Fall fehlen?'),
 ('reisen_erlebnisse', 'Welche Reiseart sollten wir einmal ausprobieren, die wir bisher noch nicht gemacht haben?'),
 ('reisen_erlebnisse',
  'Was ist dir auf Reisen wichtiger: gutes Essen, schöne Orte, Ruhe, Abenteuer oder etwas anderes?'),
 ('reisen_erlebnisse', 'Welches gemeinsame Erlebnis war sein Geld besonders wert?'),
 ('reisen_erlebnisse', 'Welche Aktivität würdest du gern einmal mit mir ausprobieren?'),
 ('reisen_erlebnisse', 'Wo würdest du gern einmal mit mir übernachten: Hütte, Hausboot, Schloss, Zelt oder Hotel?'),
 ('reisen_erlebnisse', 'Was war unser bisher schönster Moment unterwegs?'),
 ('reisen_erlebnisse', 'Welche Reise würdest du gern einmal komplett ohne großen Plan machen?'),
 ('reisen_erlebnisse', 'Was wäre für dich ein perfekter gemeinsamer Tagesausflug?'),
 ('reisen_erlebnisse', 'Welche Sehenswürdigkeit würdest du auch dann mit mir besuchen, wenn sie sehr touristisch ist?'),
 ('reisen_erlebnisse', 'Welche Landschaft möchtest du mit mir unbedingt einmal sehen?'),
 ('reisen_erlebnisse', 'Welche gemeinsame Reise sollte eher langsam und entspannt sein?'),
 ('reisen_erlebnisse', 'Bei welchem Erlebnis würdest du sagen: Das machen wir nur einmal, aber unbedingt?'),
 ('reisen_erlebnisse', 'Welche Region in unserer Nähe kennen wir noch viel zu wenig?'),
 ('reisen_erlebnisse', 'Was ist deine liebste Erinnerung an eine gemeinsame Autofahrt oder Zugfahrt?'),
 ('reisen_erlebnisse', 'Welches Essen würdest du gern an seinem Ursprungsort mit mir probieren?'),
 ('reisen_erlebnisse', 'Welche Art von Unterkunft macht einen Urlaub für dich besonders?'),
 ('reisen_erlebnisse', 'Was sollten wir auf unserer nächsten Reise bewusst weniger planen?'),
 ('reisen_erlebnisse', 'Welches kleine Abenteuer könnten wir schon in den nächsten vier Wochen machen?'),
 ('zuhause_rituale', 'Welche Ecke zuhause fühlt sich für dich am gemütlichsten an?'),
 ('zuhause_rituale', 'Welches gemeinsame Ritual am Morgen oder Abend magst du besonders?'),
 ('zuhause_rituale', 'Was könnten wir zuhause verändern, damit es sich noch mehr nach uns anfühlt?'),
 ('zuhause_rituale', 'Welche gemeinsame Mahlzeit sollte ein festes Ritual werden?'),
 ('zuhause_rituale', 'Was gehört für dich zu einem perfekten Abend zuhause?'),
 ('zuhause_rituale', 'Welche kleine Tradition sollten wir für Sonntage einführen?'),
 ('zuhause_rituale', 'Was ist zuhause für dich wichtiger: Ordnung, Gemütlichkeit, Ruhe oder Leben?'),
 ('zuhause_rituale', 'Welche Sache in unserer Wohnung oder unserem Haus erzählt am meisten über uns?'),
 ('zuhause_rituale', 'Welchen Raum oder Bereich würdest du gern gemeinsam neu gestalten?'),
 ('zuhause_rituale', 'Welche Musik gehört für dich zu einem gemütlichen Abend zuhause?'),
 ('zuhause_rituale', 'Was sollten wir zuhause öfter gemeinsam machen statt jeder für sich?'),
 ('zuhause_rituale', 'Welche kleine Wochenendroutine würde dir gefallen?'),
 ('zuhause_rituale', 'Welcher Duft erinnert dich an Zuhause?'),
 ('zuhause_rituale', 'Welche Sache sollte in unserem Zuhause niemals fehlen?'),
 ('zuhause_rituale', 'Was macht einen Ort für dich wirklich zu einem gemeinsamen Zuhause?'),
 ('persoenlichkeit', 'Welche Eigenschaft an dir selbst magst du heute mehr als früher?'),
 ('persoenlichkeit', 'Was möchtest du gerade über dich selbst besser verstehen?'),
 ('persoenlichkeit', 'Welche Sache gibt dir zuverlässig Selbstvertrauen?'),
 ('persoenlichkeit', 'Was brauchst du, um dich wirklich erholt zu fühlen?'),
 ('persoenlichkeit', 'Welche Eigenschaft würdest du gern ein bisschen stärker ausleben?'),
 ('persoenlichkeit', 'Was fällt dir leichter, wenn jemand an dich glaubt?'),
 ('persoenlichkeit', 'Welche Art von Kompliment bedeutet dir am meisten?'),
 ('persoenlichkeit', 'Wann fühlst du dich am meisten wie du selbst?'),
 ('persoenlichkeit', 'Welche Sache möchtest du dir selbst öfter zugestehen?'),
 ('persoenlichkeit', 'Was motiviert dich nachhaltiger: Vorfreude, Anerkennung, Neugier oder ein klares Ziel?'),
 ('persoenlichkeit', 'Welche Seite von dir kommt in unserer Beziehung besonders gut zum Vorschein?'),
 ('persoenlichkeit', 'Was würdest du deinem jüngeren Ich gern über dein heutiges Leben erzählen?'),
 ('persoenlichkeit', 'Welche Sache möchtest du nicht mehr so ernst nehmen?'),
 ('persoenlichkeit', 'Was hilft dir, eine schwierige Entscheidung zu treffen?'),
 ('persoenlichkeit', 'Welche persönliche Entwicklung der letzten Jahre macht dich stolz?')]

assert len(BUILTIN_QUESTIONS) >= 365
assert len({text for _, text in BUILTIN_QUESTIONS}) == len(BUILTIN_QUESTIONS)
